info:
  contact: {}
  description: This is a ApiGatway.
  title: Api-Ruta3
  version: "1.0"
paths:
  /test:
    get:
      description: Api test
      operationId: test
      responses: {}
swagger: "2.0"
